import "../global.css";
import { Inter } from "next/font/google";
import LocalFont from "next/font/local";
import { Metadata } from "next";
import { Analytics } from "./components/analytics";

export const metadata: Metadata = {
  title: {
    default: "R Sahani",
    template: "%s | R Sahani",
  },
  description:
    "Hey, Im Rahul Sahani. I'm a full-stack developer and a designer.",

  authors: [
    {
      name: "Rahul Sahani",
      url: "https://rsahani.tech",
    },
  ],
  keywords: [
    "portfolio",
    "developer",
    "designer",
    "react",
    "typescript",
    "tailwindcss",
    "threejs",
    "nextjs",
    "webgl",
    "webxr",
    "webdev",
    "webdesign",
    "webdevelopment",
    "webdeveloper",
    "webdesigner",
    "creative",
    "design",
    "ui",
    "ux",
    "frontend",
    "fullstack",
    "software",
    "engineer",
    "programmer",
    "coding",
    "programming",
    "javascript",
    "html",
    "css",
    "nodejs",
    "python",
    "java",
    "c",
    "c++",
    "rust",
    "go",
    "php",
    "ruby",
    "swift",
    "kotlin",
    "dart",
    "sql",
    "nosql",
    "mongodb",
    "firebase",
    "postgresql",
    "mysql",
    "sqlite",
    "docker",
    "kubernetes",
    "aws",
    "azure",
    "gcp",
    "cloud",
    "serverless",
    "rest",
    "graphql",
    "api",
    "microservices",
    "devops",
    "agile",
    "scrum",
    "kanban",
    "git",
    "github",
    "gitlab",
    "bitbucket",
    "jira",
    "figma",
    "adobe",
    "photoshop",
    "illustrator",
    "xd",
    "sketch",
    "blender",
    "unity",
    "unreal",
    "ar",
    "vr",
    "xr",
    "virtualreality",
    "augmentedreality",
    "mixedreality",
    "gamedev",
    "game",
    "gaming",
    "mobile",
    "android",
    "ios",
    "reactnative",
    "flutter",
    "ionic",
    "native",
    "pwa",
    "jamstack",
    "static",
    "dynamic",
    "server",
    "client",
    "frontend",
    "backend",
    "fullstack",
    "software",
    "engineer",
    "programmer",
    "coding",
    "programming",
    "javascript",
    "html",
    "css",
    "nodejs",
    "python",
    "java",
    "c",
    "c++",
    "rust",
    "go",
    "php",
    "ruby",
    "swift",
    "kotlin",
    "dart",
    "sql",
    "nosql",
    "mongodb",
    "firebase",
    "postgresql",
    "mysql",
    "sqlite",
    "docker",
    "kubernetes",
    "aws",
    "azure",
    "gcp",
    "cloud",
    "serverless",
    "rest",
    "graphql",
    "api",
    "microservices",
    "devops",
    "agile",
    "scrum",
    "kanban",
    "git",
    "github",
    "gitlab",
    "bitbucket",
    "jira",
    "figma",
    "adobe",
    "photoshop",
    "illustrator",
    "xd",
    "sketch",
    "blender",
    "unity",
    "unreal",
    "ar",
    "vr",
    "xr",
    "virtualreality",
    "augmentedreality",
    "mixedreality",
    "gamedev",
    "game",
    "gaming",
    "mobile",
    "android",
    "ios",
    "reactnative",
    "flutter",
    "ionic",
    "native",
    "pwa",
    "jamstack",
    "static",
    "dynamic",
    "server",
    "client",
  ],
  publisher: "Rahul Sahani",
  openGraph: {
    title: "R Sahani",
    description:
      "Hey, Im Rahul Sahani. I'm a full-stack developer and a designer.",
    url: "https://github.com/rahul-sahani04",
    siteName: "R Sahani",
    images: [
      {
        url: "https://rsahani.tech/og.png",
        width: 1920,
        height: 1080,
      },
    ],
    locale: "en-US",
    type: "website",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  twitter: {
    title: "R Sahani",
    card: "summary_large_image",
  },
  icons: {
    shortcut: "/favicon.png",
    apple: "/favicon.png",
    icon: "/favicon.png",
  },
};
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const calSans = LocalFont({
  src: "../public/fonts/CalSans-SemiBold.ttf",
  variable: "--font-calsans",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={[inter.variable, calSans.variable].join(" ")}>
      <head>
        <Analytics />
        <link rel="icon" href="/favicon.png" />
      </head>
      <body
        className={`bg-black
          overflow-x-hidden
          ${
          process.env.NODE_ENV === "development" ? "debug-screens" : undefined
        }`}
      >
        {children}
      </body>
    </html>
  );
}
