name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main  # Change to your default branch if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.9.0'  # Ensure this matches the required Node.js version

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Export static site
        run: yarn next export

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./next  # Change to the directory where your exported site is located
